services:
  redis:
    image: redis:latest
    container_name: rento-redis
    ports:
      - '${REDIS_PORT}:6379'

  mailpit:
    image: axllent/mailpit:latest
    container_name: rento-mail
    ports:
      - '1025:1025'
      - '8025:8025'

  minio:
    image: quay.io/minio/minio:latest
    container_name: rento-s3
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_REGION_NAME: ${AWS_DEFAULT_REGION}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
